### ISSUE TITLE
Screen flashing everywhere even when over 155 at the airport

### ISSUE THREAD

**Issue by crKtv** [ESX-PUBLIC/esx_speed_radar#1]
Title

**Comment by Cha0sNighT** [comment]
just change 155 in L117 

`if((GetEntitySpeed(PlayerPed) * 3.6) >155)then`

I put it to 200 personally

**Comment by crKtv** [comment]
My issue is that it should only flash NEAR the radar coordinates, I tried changing the distance from the radar to 15 at 
`if(GetDistanceBetweenCoords(coords_ped, 1368.90, 671.22, 79.912, true) < 15 ) then`
but still flashes at the airport, I just want it to flash near the radar coordinates

**Comment by Cha0sNighT** [comment]
it flash at the radar, it's quick, the effect when you're up 155 is the "speed effect" 
Flash > `StartScreenEffect('SwitchShortMichaelIn',  400,  false)`
Speed Effect > `StartScreenEffect('RaceTurbo',  0,  false)`

**Comment by crKtv** [comment]
Oh ok my bad then, didn't notice it was supposed to have that effect apart from the flashing.
Thanks man, issue closed!
